Repository raymag/floesia-api, pull requests merged in 2020-10, with the labels that each got.

#10 add poem storing and poem editing routes
  src/controllers/AuthorController.js
  src/controllers/PoemController.js
  src/models/Author.js
  src/models/Poem.js
  src/routes.js
Labels: enhancement

#15 add .env_example
  .env_example
Labels: documentation

#16 Add Dev Environment Guidelines to README.md
  README.md
Labels: documentation

#17 added get author by id route
  package-lock.json
  src/controllers/AuthorController.js
  src/routes.js
Labels: enhancement

#19 remove package-lock.json
  package-lock.json
  src/controllers/AuthorController.js
Labels: bug

#22 Issue 18/route poems by author
  package-lock.json
  src/controllers/PoemController.js
  src/routes.js
Labels: enhancement

#27 Added route for updating poems (title or body) using poem id
  package-lock.json
  src/controllers/PoemController.js
  src/routes.js
Labels: enhancement, hacktoberfest-accepted

#28 add owner verification to Poem Updating route
  package-lock.json
  src/controllers/PoemController.js
Labels: enhancement, good first issue

#31 Added route to remove poem and login also returns author info
  package-lock.json
  src/controllers/AuthController.js
  src/controllers/PoemController.js
  src/routes.js
Labels: hacktoberfest-accepted

#32 Fix poem updating route's http method
  package-lock.json
  src/controllers/PoemController.js
  src/routes.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#34 feat: poem listing route now populates author field
  src/controllers/PoemController.js
  src/models/Poem.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#36 make poem model's fields required
  src/models/Poem.js
Labels: enhancement

#37 add get one poem with _id route
  src/controllers/PoemController.js
  src/routes.js
Labels: enhancement

#38 Add route for storing hearts
  src/controllers/HeartController.js
  src/routes.js
Labels: enhancement, hacktoberfest-accepted

#41 add route for listing all given hearts of an author
  src/controllers/AuthController.js
  src/controllers/HeartController.js
  src/routes.js
Labels: enhancement

#42 Add heart removing route
  src/controllers/HeartController.js
  src/routes.js
Labels: enhancement

#44 feat: quick fix
  src/controllers/HeartController.js
Labels: bug

#46 Add poem trending route
  src/controllers/PoemController.js
  src/routes.js
Labels: enhancement, hacktoberfest-accepted

#47 Fix poem trending
  src/controllers/PoemController.js
Labels: bug, enhancement

#48 Fix author popoulation in poem trending
  src/controllers/PoemController.js
Labels: bug
